site_name: 'カドゥケウスZ/NB RTAガイド'
site_author: "tdnossan"
extra_css:
  - 'css/custom.css'
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
extra_javascript:
  - js/custom.js
nav:
    - Home: index.md
    - RTA前の準備: preparation.md
    - Wiiリモコンの操作方法: wiimote.md
    - 基礎知識: basic.md
    - カドゥケウスZ:
        - Any% Normal: tcso_normal/index.md
        - ギルス攻略: tcso_normal/guilt.md
    - カドゥケウス NEW BLOOD:
        - Any% Normal: tcnb_normal/index.md
        - All XS: tcnb_allxs/index.md
theme:
  name: 'material'
  language: ja
  palette:
    - scheme: default
      primary: 'teal'
      accent: 'pink'
      toggle:
        icon:  material/toggle-switch-off-outline
        name: ダークモードに切り替えます。
    - scheme: slate
      primary: 'deep purple'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch
        name: ライトモードに切り替えます。
  features:
    ##- navigation.instant     ## mkdocs for MaterialのSPA対応 # SPAだとlive-editが効かないので無効化
    - navigation.tabs        ## トップレベル項目を画面上部メニューにタブ表示
    - navigation.sections  ## 項目のセクション表示 
    - navigation.expand    ## 初期表示で全てのページ展開を有効化
    - navigation.top         ## ページTOP遷移ボタンを有効化
    - navigation.path        ## パンくずリスト　動かない？
    ## - toc.integrate       ## 画面左右のメニューを統合
    - header.autohide        ## スクロールしたときヘッダーを自動的に非表示にする
    ##- search.suggest         ## 検索の候補リスト表示を表示する
    - search.highlight       ## 検索で一致した結果をハイライトする
    ##- content.code.copy      ## コードコピー機能
  font:
    text: Noto Sans JP
    code: Inconsolata
extra:
  homepage: https://github.com/tdnossan/speedrun/
  annotate: true # ページの右上にアノテーションボタンを表示
  generator: false
  social:
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/tdnossan
markdown_extensions:
  - attr_list
  - admonition # アラート修飾の設定
  - footnotes # 注釈機能
  - pymdownx.details # コンテンツの折りたたみ設定
  - pymdownx.magiclink # URLっぽいものは自動リンク機能
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3
plugins:
  search:
    lang: 'ja'
  exclude:
      glob:
        - "**/.git/*"
        - "**/node_modules/*"
        - "**/memo.md"
        - "**/yukkuri.md"
        - "**/kaisetu.md"